spring.application.name=portfolio-backend
server.error.include-message=always

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/portfolio_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

adzuna.app.id=c2e6621c
adzuna.app.key=7909703d54a4444d5b71a5920233b698

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:jaiminpanchal939@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:usto movs oiqo ggvg}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.starttls.required=${SPRING_MAIL_STARTTLS_REQUIRED:true}

# Set your permanent real Google Meet link here:
jaimin.meet.link=https://meet.google.com/ira-yipn-ihu